# FastAPI Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-api-pod
  template:
    metadata:
      labels:                   
        app: fast-api-pod       
        version: svc                      #
      annotations:                        # Istio を使用するためのアノテーション
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: "128m"
        sidecar.istio.io/proxyMemory: "128Mi"
        proxy.istio.io/config: "{'concurrency':'4'}"
    spec:
      containers:
      - name: fast-api-container
        image: gcr.io/my-project2-303004/fast-api-image-gke:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http-server
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker --reload"]
        resources:
          limits:
            cpu: 500m
            memory: "300Mi"

---
# vegeta pod
apiVersion: apps/v1         
kind: Deployment            
metadata:
  name: vegeta-attack-pod
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: vegeta-attack-pod     
  template:                      
    metadata:
      labels:                    
        app: vegeta-attack-pod   
      annotations:               # Istio を使用するためのアノテーション
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: "128m"
        sidecar.istio.io/proxyMemory: "128Mi"
        proxy.istio.io/config: "{'concurrency':'16'}"
    spec:
      containers:               
      - name: vegeta-attack-container
        image: gcr.io/my-project2-303004/vegeta-attack-image-gke:latest 
        imagePullPolicy: Always
        command: ["tail","-f","/dev/null"]          
        resources:
          requests:
            cpu: 1000m
            memory: "1000Mi"
        volumeMounts:
          - name: vegeta-attack-configmap-volumes
            mountPath: "/vegeta/configmap"
            readOnly: true
      volumes:                      # ConfigMap 用のボリューム | ConfigMap は、ファイルとしてマウントすることで Pod から使用できる
        - name: vegeta-attack-configmap-volumes
          configMap:
            name: vegeta-attack-configmap
